# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Friend')),
            ],
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friend_to_add',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friendships',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
