# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171004_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', through='users.Friendships', to='users.UserProfile'),
        ),
    ]
